name: tailscale-rdesktop-blacksmith

on:
  workflow_dispatch:

jobs:
  rdesktop-test:
    name: Tailscale SSH Machine - Blacksmith
    uses: ./.github/workflows/reusable-tailscale-rdesktop.yml
    with:
      runs-on: "blacksmith-2vcpu-ubuntu-2404"
      image: "ghcr.io/gbraad-gaming/minecraft-launcher:latest"
      hostname: "gaming-minecraft-client-1"
    secrets: inherit
